import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import React from "react";
import { getDictionary } from "@/app/lang/dictionaries";
import Navbar from "@/app/_components/Navbar";
import { ILang } from "@/app/lang/dictionaries/ILang";
import StyledComponentsRegistry from "@/app/_lib/registry";
import Lang from "@/app/_components/_utils/Lang";
import Header from "@/app/_components/Header";
import Scroll from "@/app/_components/_utils/Scroll";
import Footer from "@/app/_components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const lang: ILang = await getDictionary();
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <div></div>
          <Navbar lang={lang} />
          <Header lang={lang} />

          <Lang lang={lang} />
          <Scroll />
          {children}
          <Footer lang={lang} />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
